### ISSUE TITLE
Computing unique values

### ISSUE THREAD

**Issue by spcoyne** [uc-cfss/Discussion#10]
I'm trying to compute the number of unique values for the iris dataset. I'm using the following code:

output <- vector("double", ncol(iris))
for (i in seq_long(iris)) {
  output[[i]] <- unique(iris[[i]])
}
output

But I get the following error/output:

Error in output[[i]] <- unique(iris[[i]]) : 
  more elements supplied than there are to replace

> output
> [1] 0 0 0 0 0

Any thoughts?

**Comment by bensoltoff** [comment]
Try running unique(iris[[1]]). What is the result? Is this what you
expected?

**Comment by spcoyne** [comment]
that gives the same output/error

**Comment by bensoltoff** [comment]
Even if you just run that line of code in the console? Literally
unique(iris[[1]])

On Oct 16, 2016 9:46 PM, "spcoyne" notifications@github.com wrote:

that gives the same output/error

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/uc-cfss/Discussion/issues/10#issuecomment-254100456,
or mute the thread

**Comment by spcoyne** [comment]
oh! with that i get a list of each unique value, which wasn't what I was expecting, but I think if I combine that with some sort of count command I might get what I'm looking for?

**Comment by bensoltoff** [comment]
Yeah, that's on the right track.
