### ISSUE TITLE
Issue in Practice transforming college education-Report the number as the total number of schools

### ISSUE THREAD

**Issue by Xinyi-Cai** [uc-cfss/Discussion#167]
Can anyone help me with this problem? 
I double checked my code and found no difference with the solution, yet the result does not show up. 
![截屏2021-01-21 上午11 20 39](https://user-images.githubusercontent.com/77372754/105275914-3c25ae80-5bdb-11eb-81e0-b6b7ce78eda7.png)

**Comment by bensoltoff** [comment]
Check your last `filter()` function. You misspelled "University". Since there is no college with the name of "Univeristy of Chicago" the result of the filter operation is a data frame with 0 rows.

Spelling is extremely important when writing code as the computer will interpret your instructions literally.

![](https://media.giphy.com/media/jISXU1iSd95Dbd6G82/giphy.gif)

**Comment by Xinyi-Cai** [comment]
Thank you so much!
