### ISSUE TITLE
Warning message on Question 5: Ignoring unknown parameters: fill 

### ISSUE THREAD

**Issue by akerah** [uc-cfss/Discussion#173]
Hello, 

   I am getting this error message when I try to graph my months

month_month<-mass_shootings %>%group_by(month)%>% count()

  ggplot(data=month_month, mapping = aes(x=month,y=n)) + 
  geom_freqpoly(stat = "identity",)+
  labs(title = "Number of mass shootings by Month",
       x = "Month", y= "Number of shootings" )

**Comment by fdicera** [comment]
It looks like you have an extra comma after `"identity"` which might be causing the warning message. I would try removing it, and seeing if that helps.

**Comment by akerah** [comment]
Did not help. Am I approaching this correctly?

**Comment by fdicera** [comment]
For Question 5, it asks for a **bar chart** of the shootings per month, so `geom_bar()` is the function you want to use. Since `geom_bar()` uses the "count" stat by default, you don't need to do your first step of grouping the months and counting them (as the counts for each month will automatically go on the y-axis). You'll want to adjust your inputs into `ggplot()` accordingly (remember that `geom_bar()` only needs an x-variable). You'll also need to think about how to order the months chronologically on your plot ([this resource may help](https://stackoverflow.com/questions/36020146/how-can-i-order-the-months-chronologically-in-ggplot2-short-of-writing-the-month)).

**Comment by akerah** [comment]
Thank you, I fixed my issue.
