### ISSUE TITLE
Trouble pushing to GitHub

### ISSUE THREAD

**Issue by futureofmaya** [uc-cfss/Discussion#22]
@carlyoffidani and I have been trying to push to GitHub, but to no avail. It gives us an error message that our data file is too big (147mb), even if we're just pushing other files in that project. So... nothing is on GitHub and I'm a bit concerned about how it will eventually get there.

**Comment by bensoltoff** [comment]
You cannot store files larger than 100mb on Github. Even if you removed it from the repo, it probably was tracked previously. Unfortunately removing the file from your commit history is [a pain](http://stackoverflow.com/questions/8740187/git-how-to-remove-file-from-historical-commit) - afterall, the whole point of Git is to track all of these changes.

Your best option is to use [Git Large File Storage](https://git-lfs.github.com/) on your repo. This allows you to commit large data files and track changes and still use GitHub. [This video explains how it works in pretty basic terms](https://www.youtube.com/watch?v=uLR1RNqJ1Mw). If you have trouble installing Git LFS and getting it to work, @jmausolf can probably help you install it during office hours tomorrow. I'll also be in the office tomorrow (times TBD - I'll send an email once I know what my hours will be)

@JordanAMartin might also find this interesting, since I remember you had pretty large data files too. If I'm remembering incorrectly, just ignore this

**Comment by futureofmaya** [comment]
Ok, thank you! Will look into this soon and report back.
