### ISSUE TITLE
Shiny Apps

### ISSUE THREAD

**Issue by futureofmaya** [uc-cfss/Discussion#26]
Hi there, me again. I know. 

So I managed to get the shiny app on shinyapps.io. It says it's up and running, and everything looks as it should. It also runs fine in R Studio. However... the link to it just says "Please wait" and then eventually devolves into "502 Bad Gateway." I've redeployed it a few times, same thing. Through some quick Googling, it seems that this just happens from time to time? 

Here's the link: https://ritabiagioli.shinyapps.io/finalproject2/

**Comment by futureofmaya** [comment]
Additional problems that I'm having: 

1) I'm stuck and can't push again for some reason. Don't know. 
2) Now, when I try to run the app in my finalproject 2 folder, it crashes R. It's done it like four times. 
3) When I try to run the app in my HW10 folder, it gives me this error: ERROR: invalid multibyte string, element 3

I seriously don't have a clue anymore. I don't know what to do.

**Comment by futureofmaya** [comment]
Well, finalproject2 isn't crashing anymore. So that's something.

**Comment by carlyoffidani** [comment]
To corroborate, I have been trying to run the same code- in the final project folder it words, as all one text, but when we try to split it up into the ui and server, it just loads a blank grey screen. In the slides it mentioned that we shouldn't call the function shinyApp(ui = ui, server = server), so I tried removing that.. still no luck. also tried entering that code only in the console but not in the code itself, nothing.

I also created a new repo that was et up as a shiny already and tried putting the code in separate files in the pre-set shiny template.. still nothing

**Comment by bensoltoff** [comment]
I'm having issues pulling the latest changes from `fp-futureofmaya`, so I cloned Rita's `hw10` repo. [I just pushed a commit that solves the problems.](https://github.com/futureofmaya/hw10/commit/01564d4efc2e9d3e3b13d4b9b519542a143485ea) There were two main issues splitting the app between 2 files.

1. `tweet_words` and all the code outside of the UI and server objects needs to be stored in `server.R`
1. Because the word input uses `sort(unique(tweet_words$word))` to generate the list of potential terms, it has to be created inside the server function. I completely forgot about that earlier. See [our tutorial](https://uc-cfss.github.io/shiny01_abc.html#11_using_uioutput()_to_create_ui_elements_dynamically) for more details on this

You should be able to publish the app from this commit to shinyapps.io. Note that it still needs to be refined before publishing. At this point, I don't think you even use `tweet_dates2`. Delete this code from `server.R` unless you need it for a plot or table. Otherwise it is computationally intensive to calculate and you'll get charged for more server time on shinyapps.io anytime someone starts your app
