### ISSUE TITLE
Lab on Wednesday

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/Discussion#31]
@uc-cfss/students because of MLK day, lab this evening is canceled (so is class today). We will hold a makeup lab on Wednesday from 4:30-5:20 in **146 Saieh**.

Because of this, homework 02 is now due by **11:59pm on Wednesday**. If you have significant problems hindering you from submitting it before class, come to lab and we can help troubleshoot them with you.

**Comment by ifarah** [comment]
Hello professor,
I'm about to finish with the homework but I was playing basketball and I think I broke my finger. I'm at the er.
My name is Irene Farah

Sent from my iPhone

On Jan 16, 2017, at 1:19 PM, Benjamin Soltoff <notifications@github.com<mailto:notifications@github.com>> wrote:


@uc-cfss/students<https://github.com/orgs/uc-cfss/teams/students> because of MLK day, lab this evening is canceled (so is class today). We will hold a makeup lab on Wednesday from 4:30-5:20 in 146 Saieh.

Because of this, homework 02 is now due by 11:59pm on Wednesday. If you have significant problems hindering you from submitting it before class, come to lab and we can help troubleshoot them with you.

-
