### ISSUE TITLE
sorting months into seasons

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#6]
Hey all,

Wondering how people have been handling this task. I was looking for help on stackoverflow, but all their suggestions seem very complicated (below I put a few things i tried).

Season <- factor(quarters(as.chron(month), 
                    labels = c("winter", "spring", "summer", "fall")) %>%
                   count(Season)

gun_deaths %>%
  months2season = {
    12:0, 1:0, 2:0, #Dec/Jan/Feb are all winter (season 0)
    3:1, 4:1, 5:1, #Mar/Apr/May are all spring (season 1)
    6:2, 7:2, 8:2, #Jun/Jul/Aug are all summer (season 2)
    9:3, 10:3, 11:3 #sept/oct/nov are all fall (season 3)
  }

Neither of these have worked for me, but I think it's because I don't quite understand where our datasets variables fit in in this code..

I know there must be an easier way, but I have been trying to re-assign the variables and it keeps telling me the variable "month" does not exist. 

gun__deaths %>%
  Winter <- summarise(month, 1:3)

any ideas?

**Comment by bensoltoff** [comment]
A few things:
1. Make sure you don't mix pipes with assignments. This
   
   ``` r
   gun__deaths %>%
   Winter <- summarise(month, 1:3)
   ```
   
   Is bad. The assignment should come first, like this
   
   ``` r
   Winter <- gun__deaths %>%
     summarise(month, 1:3)
   ```
   
   (Of course, you also have an error in `summarise(month, 1:3)`, but that's another issue)
2. Your first approach requires the `chron` library. Make sure you have installed and loaded it first in the code before trying to use these functions.
3. In your second approach, you haven't enclosed `months2seasons` in the `mutate()` function. If you want to create new variables within a pipe like this, it should look something like this:

``` r
gun_deaths %>%
  mutate(months2season = {
  12:0, 1:0, 2:0, #Dec/Jan/Feb are all winter (season 0)
  3:1, 4:1, 5:1, #Mar/Apr/May are all spring (season 1)
  6:2, 7:2, 8:2, #Jun/Jul/Aug are all summer (season 2)
  9:3, 10:3, 11:3 #sept/oct/nov are all fall (season 3)
})
```

But as you discovered, this code doesn't produce a new variable because it doesn't implement a function. You could write a series of `ifelse()` statements to create a new variable (examples of `if/else` expressions are in the reading for tomorrow).

An easier approach makes use of the `cut()` function. Type `?cut` in the console to get more information on how this function works.
