### ISSUE TITLE
Trying to combine Supreme Court Data sets

### ISSUE THREAD

**Issue by spcoyne** [uc-cfss/Discussion#9]
I'm trying to bind the supreme court data sets, and I've come up with something that looks like this:

scdbv <- scdbv_mod %>%
  mutate(docket, as.character()) %>%
  bind_rows(scdbv_leg %>%
  mutate_each(funs(as.numeric), adminAction, adminActionState))

Which I think is close to correct, but I keep getting the following error: 
Error in eval(substitute(expr), envir, enclos) : 
  wrong result size (0), expected 78233 or 1

**Comment by bensoltoff** [comment]
Looks good, just remember that whenever you use the `mutate()` function, you need to specify like `mutate(docket = as.character(docket))`. Otherwise you are trying to pass `docket` and `as.character()` as two separate arguments to the `mutate()` function, whereas you really want just one argument (`docket = as.character(docket)`) which will become the new column
